name: 'Auto update rules'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.11.9/sing-box_1.11.9_linux_amd64.deb"
      run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Run script
      run: |
        mkdir -p ./output/
        python convert.py

    - name: Archive files
      run: tar -cvf ./output/rules_archive.tar --exclude="*.tar" -C ./output/ .

    - name: Move files to rule_json and rule_srs
      run: |
        mkdir -p ./rule_json/
        mkdir -p ./rule_srs/
        tar --wildcards -xvf ./output/rules_archive.tar -C ./rule_json/ '*.json'
        tar --wildcards -xvf ./output/rules_archive.tar -C ./rule_srs/ '*.srs'

    - name: Commit and push config.json
      env:
        TZ: America/New_York
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions bot"
        git add ./rule_json/*.json
        git add ./rule_srs/*.srs

        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m ":pencil: Fetch at $(date +"%Y-%m-%d %H:%M")" -a
          git push
        fi
